# Generated by Django 3.1 on 2020-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
