# Generated by Django 3.1 on 2020-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subject_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
