# Generated by Django 3.1 on 2020-10-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_subjectsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_date', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.subject')),
            ],
        ),
    ]
